### ISSUE TITLE
购买按钮文字必须完全匹配

### ISSUE THREAD

**Issue by chienxx** [boring-keyboard/bot#2]
试了kbd的链接，因为店铺有优惠券，购买按钮文字是`领券购买`不会跳转支付，建议也模糊匹配。

**Comment by boring-keyboard** [comment]
> 试了kbd的链接，因为店铺有优惠券，购买按钮文字是`领券购买`不会跳转支付，建议也模糊匹配。

试了一下，不是因为按钮文字没有匹配导致，是因为选择完规格后立即点击```领券购买```过快导致页面认为没有选择规格。如果加上100ms左右延迟再点击大概率可以正常提交。我还没有找到一个合适的页面特征来识别出最佳点击时机。

**Comment by boring-keyboard** [comment]
加了一些延迟和重试机制，发布在0.4.3中
